Remove ramdac
ramdac drivers have been removed from xserver since version 21.0.99.1
and
https://gitlab.freedesktop.org/xorg/xserver/-/commit/f0385fb420158ac3bc1c4c325431ffc5c62344bb
resulting in the following build failure:

In file included from trident_bank.c:37:
trident.h:41:10: fatal error: xf86RamDac.h: No such file or directory
   41 | #include "xf86RamDac.h"
      |          ^~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/c81ac8075af257e8626d9d097270be7a7b4a1496

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>